version: '3.8'

networks:
  caixa-network:
    driver: bridge

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourPassword123!
      - MSSQL_PID=Express
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    networks:
      - caixa-network
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourPassword123! -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 5s
      retries: 10
    command: >
      /bin/bash -c "
      /opt/mssql/bin/sqlservr & 
      sleep 15;
      /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P YourPassword123! -Q 'IF DB_ID(''caixa_dev'') IS NULL CREATE DATABASE caixa_dev';
      wait"

  quarkus-app:
    container_name: quarkus-app
    build:
      context: .  # contexto raiz do projeto
      dockerfile: src/main/docker/Dockerfile.jvm
    depends_on:
      - sqlserver
    ports:
      - "8080:8080"
    networks:
      - caixa-network

volumes:
  sqlserver_data:
